base_classes = {
    "soldier": [
        "fighting spirit",
        "field command",
        "scars of battle",
        "military conditioning",
        "veterancy",
    ],
    "shaman": ["mogdrogen's pact"],
    "necromancer": [
        "spectral binding",
        "call of the grave",
        "mark of torment",
        "foul eruption",
    ],
    "occultist": ["curse of frailty", "blood of dreeg"],
    "oathkeeper": [
        "celestial p",
        "presence of virtue",
        "ascension",
        "clarity of purpose",
        "resilience",
        "haven",
    ],
    "inquisitor": [
        "inquisitor seal",
        "arcane empowerment",
        "word of renewal",
        "vigor",
        "steel resolve",
        "deadly aim",
    ],
    "nightblade": [
        "pneumatic burst",
        "veil of shadow",
        "phantasmal armor",
    ],
    "demolitionist": ["flame touched", "temper", "blast shield", "vindictive flame", "thermite mine"],
    "arcanist": [
        "overload",
        "elemental balance",
        "maiven's sphere of protection",
        "mirror of e",
        "inner focus",
        "arcane will",
        "nullification",
    ],
}
