base_skills = {
    "savagery": ["tenacity of the board", "storm touched"],
    "counter strike": [],
    "mogdrogen's pact": ["heart of the wild", "oak skin"],
    "menhir's will": [],
    "fighting spirit": [],
    "field command": ["squad tactics"],
    "military conditioning": [],
    "veterancy": [],
    "decorated soldier": [],
    "scars of battle": [],
    "summon familiar": ["mend flesh", "storm spirit", "lightning strike"],
    "raise skeletons": ["undead legion", "will of the crypt"],
    "spectral binding": ["spectral wrath"],
    "curse of frailty": ["vulnerability"],
    "blood of dreeg": ["aspect of the guardian"],
    "call of the grave": [],
    "mark of torment": [],
    "foul eruption": [],
    "summon hellhound": ["ember claw", "hellfire", "infernal breath"],
}
