base_skills = {
    "savagery": ["tenacity of the board", "storm touched"],
    "mogdrogen's pact": ["heart of the wild", "oak skin"],
    "field command": ["squad tactics"],
    "summon familiar": ["mend flesh", "storm spirit", "lightning strike"],
    "raise skeletons": ["undead legion", "will of the crypt"],
    "spectral binding": ["spectral wrath"],
    "curse of frailty": ["vulnerability"],
    "blood of dreeg": ["aspect of the guardian"],
    "summon hellhound": ["ember claw", "hellfire", "infernal breath"],
    "summon blight fiend": ["rotting fumes", "blight burst"],
    "bonds of bysmiel": ["manipulation"],
    "summon briarthorn": ["emboldening presence", "ground slam"],
    "wendigo totem": ["blood pact"],
    "grasping vines": ["entangling vines"],
    "veil of shadow": ["night's chill"],
    "pneumatic burst": ["shadow dance", "elemental awakening"],
    "blitz": ["blindside"],
    "maiven's sphere of protection": ["conversion"],
    "mortar trap": ["heavy ordnance", "the big one"],
    "canister bomb": ["improved casing", "ulzuin's chosen"],
    "grenado": ["high impact", "shattering blast", "ulzuin's chosen"],
    "stun jacks": ["full spread", "ulzuin's chosen"],
    "phantasmal blades": ["heart seeker", "nether edge"],
    "thermite mine": ["hellfire mine"],
}
